# Generated by Django 4.2.11 on 2024-04-04 21:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='weight',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
