# Generated by Django 4.2.11 on 2024-04-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_activity_day_activity_hours_activity_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
    ]
