# Generated by Django 4.2.11 on 2024-04-04 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_activity_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='day',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
