# Generated by Django 4.2.11 on 2024-04-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_activity_day_remove_activity_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_state',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
