# Generated by Django 4.2.11 on 2024-04-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_user_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_state',
            field=models.IntegerField(default=0),
        ),
    ]
