# Generated by Django 4.2.11 on 2024-04-04 22:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_user_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.user'),
        ),
        migrations.AddField(
            model_name='activity',
            name='weight',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
