# Generated by Django 4.2.11 on 2024-04-19 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_activity_day_activity_hours_activity_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='time',
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='from_time',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='activity',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='to_time',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='activity',
            name='day',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='activity',
            name='weight',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
