# Generated by Django 4.2.11 on 2024-04-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_remove_activity_time_activity_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
