# Generated by Django 4.2.11 on 2024-04-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_activity_activity_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_type',
            new_name='act_type',
        ),
    ]
